export function extractMermaidBlock(markdown: string): string {
  const match = markdown.match(/```mermaid\n([\s\S]*?)```/);
  return match ? match[1].trim() : '';
}

export function renderErdHtml(mermaidCode: string, title: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { --bg: #ffffff; --text: #1a1a2e; --card: #f8f9fa; --border: #dee2e6; }
    @media (prefers-color-scheme: dark) {
      :root { --bg: #1a1a2e; --text: #e0e0e0; --card: #16213e; --border: #334155; }
    }
    body { font-family: -apple-system, system-ui, sans-serif; background: var(--bg); color: var(--text); margin: 0; padding: 2rem; }
    h1 { font-size: 1.5rem; border-bottom: 2px solid var(--border); padding-bottom: 0.5rem; }
    .mermaid { background: var(--card); border-radius: 8px; padding: 2rem; border: 1px solid var(--border); }
    .meta { font-size: 0.85rem; color: #6c757d; margin-top: 1rem; }
    #theme-toggle { position: fixed; top: 1rem; right: 1rem; cursor: pointer; font-size: 1.5rem; background: none; border: none; }
  </style>
</head>
<body>
  <button id="theme-toggle" onclick="toggleTheme()">🌓</button>
  <h1>${escapeHtml(title)}</h1>
  <div class="mermaid">
${mermaidCode}
  </div>
  <p class="meta">Generated by IDDD Preview — ${new Date().toISOString().split('T')[0]}</p>
  <script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
    mermaid.initialize({
      startOnLoad: false,
      theme: window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'default',
      maxTextSize: 200000,
    });
    await mermaid.run({ querySelector: '.mermaid' });
  </script>
  <script>
    function toggleTheme() {
      document.documentElement.style.colorScheme = document.documentElement.style.colorScheme === 'dark' ? 'light' : 'dark';
      location.reload();
    }
  </script>
</body>
</html>`;
}

export interface ScreenDef {
  name: string;
  url: string;
  entity: string;
  pattern: string;
}

export function renderMockupHtml(screens: ScreenDef[], title: string): string {
  const cards = screens
    .map(
      (s) => `
    <div class="card">
      <div class="card-header">${escapeHtml(s.name)}</div>
      <div class="card-url">${escapeHtml(s.url)}</div>
      <div class="card-meta">Entity: ${escapeHtml(s.entity)} | Pattern: ${escapeHtml(s.pattern)}</div>
      <div class="card-wireframe">${wireframe(s.pattern)}</div>
    </div>`
    )
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { --bg: #ffffff; --text: #1a1a2e; --card: #f8f9fa; --border: #dee2e6; }
    @media (prefers-color-scheme: dark) { :root { --bg: #1a1a2e; --text: #e0e0e0; --card: #16213e; --border: #334155; } }
    body { font-family: -apple-system, system-ui, sans-serif; background: var(--bg); color: var(--text); margin: 0; padding: 2rem; }
    h1 { font-size: 1.5rem; border-bottom: 2px solid var(--border); padding-bottom: 0.5rem; }
    .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 1.5rem; margin-top: 1.5rem; }
    .card { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 1rem; }
    .card-header { font-weight: bold; font-size: 1.1rem; }
    .card-url { font-family: monospace; color: #6c757d; margin: 0.25rem 0; }
    .card-meta { font-size: 0.85rem; color: #6c757d; margin-bottom: 0.75rem; }
    .card-wireframe { background: var(--bg); border: 1px dashed var(--border); border-radius: 4px; padding: 1rem; font-family: monospace; font-size: 0.8rem; white-space: pre; }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <div class="grid">${cards}</div>
</body>
</html>`;
}

function wireframe(pattern: string): string {
  switch (pattern) {
    case 'list':
      return '┌─────────────────────┐\n│ [Search...]  [+New] │\n├───┬───────┬─────────┤\n│ # │ Name  │ Status  │\n├───┼───────┼─────────┤\n│ 1 │ ████  │ ██████  │\n│ 2 │ ████  │ ██████  │\n│ 3 │ ████  │ ██████  │\n└───┴───────┴─────────┘';
    case 'detail':
      return '┌─────────────────────┐\n│ ← Back     [Edit]   │\n├─────────────────────┤\n│ Title: ████████████ │\n│ Status: ██████      │\n│ Created: ██████████ │\n├─────────────────────┤\n│ [Related Items Tab] │\n└─────────────────────┘';
    case 'form':
      return '┌─────────────────────┐\n│ Create / Edit       │\n├─────────────────────┤\n│ Name:  [________]   │\n│ Email: [________]   │\n│ Role:  [▼ Select ]  │\n│                     │\n│ [Cancel] [Save]     │\n└─────────────────────┘';
    default:
      return '┌─────────────────────┐\n│ [Screen Wireframe]  │\n└─────────────────────┘';
  }
}

export interface AuditData {
  version: string;
  lastVerified: string;
  entities: { defined: number; implemented: number; missing: number };
  rules: { defined: number; implemented: number; missing: number };
  screens: { defined: number; implemented: number; missing: number };
}

export function renderAuditHtml(data: AuditData): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>IDDD Audit Report</title>
  <style>
    :root { --bg: #ffffff; --text: #1a1a2e; --card: #f8f9fa; --border: #dee2e6; --green: #28a745; --yellow: #ffc107; --red: #dc3545; }
    @media (prefers-color-scheme: dark) { :root { --bg: #1a1a2e; --text: #e0e0e0; --card: #16213e; --border: #334155; } }
    body { font-family: -apple-system, system-ui, sans-serif; background: var(--bg); color: var(--text); margin: 0; padding: 2rem; }
    h1 { font-size: 1.5rem; }
    .summary { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1rem; margin: 1.5rem 0; }
    .stat { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 1.5rem; text-align: center; }
    .stat-value { font-size: 2rem; font-weight: bold; }
    .stat-label { font-size: 0.85rem; color: #6c757d; }
    .ok { color: var(--green); }
    .warn { color: var(--yellow); }
    .err { color: var(--red); }
    .bar { height: 8px; border-radius: 4px; background: var(--border); margin-top: 0.5rem; overflow: hidden; }
    .bar-fill { height: 100%; border-radius: 4px; }
  </style>
</head>
<body>
  <h1>IDDD Audit Report</h1>
  <p>Model version: ${escapeHtml(data.version)} | Last verified: ${escapeHtml(data.lastVerified)}</p>
  <div class="summary">
    ${auditCard('Entities', data.entities)}
    ${auditCard('Business Rules', data.rules)}
    ${auditCard('UI Screens', data.screens)}
  </div>
</body>
</html>`;
}

function auditCard(
  label: string,
  data: { defined: number; implemented: number; missing: number }
): string {
  const pct = data.defined > 0 ? Math.round((data.implemented / data.defined) * 100) : 0;
  const color = pct === 100 ? 'var(--green)' : pct >= 80 ? 'var(--yellow)' : 'var(--red)';
  return `<div class="stat">
    <div class="stat-value" style="color:${color}">${data.implemented}/${data.defined}</div>
    <div class="stat-label">${escapeHtml(label)}</div>
    <div class="bar"><div class="bar-fill" style="width:${pct}%;background:${color}"></div></div>
    ${data.missing > 0 ? `<div class="stat-label err">${data.missing} missing</div>` : ''}
  </div>`;
}

export function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
